/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:05:40 GMT 2021
 */

package MVC.Models.Catalogs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import MVC.Models.BaseModels.Utilizador;
import MVC.Models.Catalogs.Utilizadores;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Utilizadores_ESTest extends Utilizadores_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      // Undeclared exception!
      try { 
        utilizadores0.classificaEncomenda(")", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      // Undeclared exception!
      try { 
        utilizadores0.aceitaEncomendaUtilizador("", ")", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Utilizadores utilizadores0 = new Utilizadores(hashMap0);
      // Undeclared exception!
      try { 
        utilizadores0.addEncomendaUtilizador("rJ]gFxYf!Ibw^ZZ!zt", "\"[Nl0uy47XnDsN 9");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizador utilizador0 = new Utilizador();
      utilizadores0.addUtilizador(utilizador0);
      utilizadores0.classificaEncomenda("", "");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizador utilizador0 = new Utilizador();
      utilizadores0.addUtilizador(utilizador0);
      utilizadores0.addEncomendaUtilizador("", "");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizador utilizador0 = new Utilizador();
      utilizadores0.addUtilizador(utilizador0);
      utilizadores0.aceitaEncomendaUtilizador("", "", false);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Utilizadores utilizadores0 = new Utilizadores(hashMap0);
      Utilizador utilizador0 = new Utilizador();
      hashMap0.putIfAbsent("MVC.Models.Catalogs.Utilizadores", utilizador0);
      utilizadores0.setDataUtilizadores(hashMap0);
      Utilizador utilizador1 = utilizadores0.getUtilizador("MVC.Models.Catalogs.Utilizadores");
      assertTrue(utilizador1.equals((Object)utilizador0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizador utilizador0 = new Utilizador();
      utilizador0.setNumeroEncomendas(1275);
      utilizadores0.addUtilizador(utilizador0);
      Utilizador utilizador1 = utilizadores0.getUtilizador("");
      assertTrue(utilizador1.equals((Object)utilizador0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Utilizadores utilizadores0 = new Utilizadores(hashMap0);
      hashMap0.put("5\"o;_)!-", (Utilizador) null);
      // Undeclared exception!
      try { 
        utilizadores0.setDataUtilizadores(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Utilizadores utilizadores0 = null;
      try {
        utilizadores0 = new Utilizadores((Map<String, Utilizador>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Utilizadores utilizadores0 = null;
      try {
        utilizadores0 = new Utilizadores((Utilizadores) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Utilizadores utilizadores0 = new Utilizadores(hashMap0);
      Utilizador utilizador0 = new Utilizador();
      hashMap0.putIfAbsent("MVC.Models.Catalogs.Utilizadores", utilizador0);
      utilizadores0.setDataUtilizadores(hashMap0);
      Map<String, Utilizador> map0 = utilizadores0.getDataUtilizadores();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Utilizadores utilizadores0 = new Utilizadores(hashMap0);
      Utilizador utilizador0 = new Utilizador();
      hashMap0.putIfAbsent("MVC.Models.Catalogs.Utilizadores", utilizador0);
      utilizadores0.setDataUtilizadores(hashMap0);
      boolean boolean0 = utilizadores0.existeUtilizador("MVC.Models.Catalogs.Utilizadores");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      boolean boolean0 = utilizadores0.existeUtilizador("NrMansPrtadorQ{*\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizador utilizador0 = new Utilizador();
      utilizadores0.addUtilizador(utilizador0);
      Utilizadores utilizadores1 = new Utilizadores(utilizadores0);
      assertFalse(utilizadores1.equals((Object)utilizadores0));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizador utilizador0 = utilizadores0.getUtilizador("");
      assertNull(utilizador0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      utilizadores0.removeUtilizador("G-iW[;OKTU");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Map<String, Utilizador> map0 = utilizadores0.getDataUtilizadores();
      Utilizadores utilizadores1 = new Utilizadores(map0);
      assertFalse(utilizadores1.equals((Object)utilizadores0));
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      Utilizadores utilizadores1 = utilizadores0.clone();
      assertNotSame(utilizadores0, utilizadores1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      String string0 = utilizadores0.toString();
      assertEquals("Utilizadores: \n[]", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Utilizadores utilizadores0 = new Utilizadores();
      // Undeclared exception!
      try { 
        utilizadores0.addUtilizador((Utilizador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.Catalogs.Utilizadores", e);
      }
  }
}
