/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:17:14 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparaQuantidadePair_ESTest extends ComparaQuantidadePair_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparaQuantidadePair comparaQuantidadePair0 = new ComparaQuantidadePair();
      Pair pair0 = mock(Pair.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(pair0).getFst();
      doReturn(0).when(pair0).getSnd();
      Pair pair1 = mock(Pair.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(pair1).getFst();
      doReturn(0).when(pair1).getSnd();
      // Undeclared exception!
      try { 
        comparaQuantidadePair0.compare(pair0, pair1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparaQuantidadePair", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparaQuantidadePair comparaQuantidadePair0 = new ComparaQuantidadePair();
      Pair pair0 = mock(Pair.class, new ViolatedAssumptionAnswer());
      doReturn(805, 1371, 0, 0).when(pair0).getSnd();
      int int0 = comparaQuantidadePair0.compare(pair0, pair0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparaQuantidadePair comparaQuantidadePair0 = new ComparaQuantidadePair();
      Pair pair0 = mock(Pair.class, new ViolatedAssumptionAnswer());
      doReturn(2574, 0).when(pair0).getSnd();
      Pair pair1 = mock(Pair.class, new ViolatedAssumptionAnswer());
      doReturn((-3220), 0).when(pair1).getSnd();
      int int0 = comparaQuantidadePair0.compare(pair0, pair1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparaQuantidadePair comparaQuantidadePair0 = new ComparaQuantidadePair();
      Pair pair0 = mock(Pair.class, new ViolatedAssumptionAnswer());
      doReturn("e#(={4R^l", "Pair").when(pair0).getFst();
      doReturn((-1986), (-1986)).when(pair0).getSnd();
      int int0 = comparaQuantidadePair0.compare(pair0, pair0);
      assertEquals(21, int0);
  }
}
