/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:08:53 GMT 2021
 */

package MVC.Views;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import MVC.Views.MessageView;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MessageView_ESTest extends MessageView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageView messageView0 = new MessageView();
      // Undeclared exception!
      try { 
        messageView0.show((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MessageView messageView0 = new MessageView();
      messageView0.show();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageView messageView0 = new MessageView();
      messageView0.show((Object) "r{)y3Yq$E");
  }
}
