/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:17:33 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Pair_ESTest extends Pair_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Pair pair0 = new Pair((String) null, 3065);
      int int0 = pair0.getSnd();
      assertEquals(3065, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Pair pair0 = new Pair("p\"~~.JT0 b[D)?d#)", (-1062));
      int int0 = pair0.getSnd();
      assertEquals((-1062), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Pair pair0 = new Pair((String) null, (-1180));
      pair0.getFst();
      assertEquals((-1180), pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Pair pair0 = new Pair("", 264);
      pair0.getFst();
      assertEquals(264, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pair pair0 = new Pair("", 0);
      Pair pair1 = pair0.clone();
      assertEquals(0, pair1.getSnd());
      assertTrue(pair1.equals((Object)pair0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Pair pair0 = new Pair("ltcxnB@2", 461);
      Pair pair1 = pair0.clone();
      assertTrue(pair1.equals((Object)pair0));
      assertEquals(461, pair1.getSnd());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Pair pair0 = null;
      try {
        pair0 = new Pair((Pair) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Pair", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Pair pair0 = new Pair();
      Pair pair1 = new Pair(pair0);
      assertEquals(0, pair1.getSnd());
      assertTrue(pair1.equals((Object)pair0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Pair pair0 = new Pair("p\"~~.JT0 b[D)?d#)", (-1062));
      pair0.getFst();
      assertEquals((-1062), pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Pair pair0 = new Pair();
      int int0 = pair0.getSnd();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      Pair pair1 = new Pair();
      boolean boolean0 = pair0.equals(pair1);
      assertEquals(0, pair1.getSnd());
      assertEquals((-50), pair0.getSnd());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      boolean boolean0 = pair0.equals(pair0);
      assertEquals((-50), pair0.getSnd());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      boolean boolean0 = pair0.equals("Oq0O ---> -50");
      assertFalse(boolean0);
      assertEquals((-50), pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      pair0.setFst("Oq0O");
      assertEquals((-50), pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      Pair pair1 = pair0.clone();
      assertTrue(pair1.equals((Object)pair0));
      assertEquals((-50), pair1.getSnd());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      pair0.setSecond(88);
      assertEquals(88, pair0.getSnd());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Pair pair0 = new Pair("Oq0O", (-50));
      String string0 = pair0.toString();
      assertEquals("Oq0O ---> -50", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Pair pair0 = new Pair();
      Pair pair1 = new Pair("", (-50));
      boolean boolean0 = pair0.equals(pair1);
      assertFalse(boolean0);
      assertEquals((-50), pair1.getSnd());
      assertEquals(0, pair0.getSnd());
  }
}
