/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:12:44 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parse_ESTest extends Parse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLinhaEncomenda("lm&JaDj,2");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEncomenda("H,*GK-Ck;0gLAHy/ N");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BDVoluntarios bDVoluntarios0 = new BDVoluntarios();
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      BDUtilizador bDUtilizador0 = new BDUtilizador(hashMap0, set0);
      BDLojas bDLojas0 = new BDLojas();
      BDTransportes bDTransportes0 = new BDTransportes();
      BDProdutos bDProdutos0 = new BDProdutos();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      Loja loja0 = new Loja();
      ArrayList<Encomenda> arrayList0 = loja0.getEncomendas_recebidas();
      BDGeral bDGeral0 = new BDGeral(bDVoluntarios0, bDUtilizador0, bDLojas0, bDTransportes0, bDProdutos0, encomendasAceites0);
      Parse parse0 = new Parse(bDGeral0, arrayList0, encomendasAceites0);
      Parse parse1 = new Parse(parse0);
      assertFalse(parse1.equals((Object)parse0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BDVoluntarios bDVoluntarios0 = new BDVoluntarios();
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      BDUtilizador bDUtilizador0 = new BDUtilizador(hashMap0, set0);
      BDLojas bDLojas0 = new BDLojas();
      BDTransportes bDTransportes0 = new BDTransportes();
      BDProdutos bDProdutos0 = new BDProdutos();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      Loja loja0 = new Loja();
      ArrayList<Encomenda> arrayList0 = loja0.getEncomendas_recebidas();
      BDGeral bDGeral0 = new BDGeral(bDVoluntarios0, bDUtilizador0, bDLojas0, bDTransportes0, bDProdutos0, encomendasAceites0);
      Parse parse0 = new Parse(bDGeral0, arrayList0, encomendasAceites0);
      BDGeral bDGeral1 = parse0.getBaseGeral();
      assertNotSame(bDGeral0, bDGeral1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.setEncomendas((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.setEa((EncomendasAceites) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseVoluntarios("\u0004k%#%2C8U<)?I,HJ!");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseUtilizador((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLojas("5Rj})M{4k6,&q)74c$");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLinhaEncomenda((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEncomendasAceites("sJ", (EncomendasAceites) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEncomenda((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEmpresaTransportes(".<");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.lerFicheiro((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.addEncomendasVoluntariosETransportes((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.addEncomendasCliente((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.addEncomendas((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BDGeral bDGeral0 = new BDGeral();
      EmpresaTransportes empresaTransportes0 = new EmpresaTransportes();
      ArrayList<Encomenda> arrayList0 = empresaTransportes0.getRegistos();
      ArrayList<String> arrayList1 = new ArrayList<String>();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites(arrayList1);
      Parse parse0 = null;
      try {
        parse0 = new Parse(bDGeral0, arrayList0, encomendasAceites0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("BDGeral", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Parse parse0 = new Parse();
      ArrayList<Encomenda> arrayList0 = new ArrayList<Encomenda>();
      parse0.addEncomendasVoluntariosETransportes(arrayList0);
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BDVoluntarios bDVoluntarios0 = new BDVoluntarios();
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      BDUtilizador bDUtilizador0 = new BDUtilizador(hashMap0, set0);
      BDLojas bDLojas0 = new BDLojas();
      BDTransportes bDTransportes0 = new BDTransportes();
      BDProdutos bDProdutos0 = new BDProdutos();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      BDGeral bDGeral0 = new BDGeral(bDVoluntarios0, bDUtilizador0, bDLojas0, bDTransportes0, bDProdutos0, encomendasAceites0);
      Loja loja0 = new Loja();
      ArrayList<Encomenda> arrayList0 = loja0.getEncomendas_recebidas();
      Parse parse0 = new Parse(bDGeral0, arrayList0, encomendasAceites0);
      parse0.addEncomendasCliente(arrayList0);
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Parse parse0 = new Parse();
      ArrayList<Encomenda> arrayList0 = new ArrayList<Encomenda>();
      parse0.addEncomendas(arrayList0);
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BDVoluntarios bDVoluntarios0 = new BDVoluntarios();
      HashMap<String, Utilizador> hashMap0 = new HashMap<String, Utilizador>();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      BDUtilizador bDUtilizador0 = new BDUtilizador(hashMap0, set0);
      BDLojas bDLojas0 = new BDLojas();
      BDTransportes bDTransportes0 = new BDTransportes();
      BDProdutos bDProdutos0 = new BDProdutos();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      BDGeral bDGeral0 = new BDGeral(bDVoluntarios0, bDUtilizador0, bDLojas0, bDTransportes0, bDProdutos0, encomendasAceites0);
      Loja loja0 = new Loja();
      ArrayList<Encomenda> arrayList0 = loja0.getEncomendas_recebidas();
      Parse parse0 = new Parse(bDGeral0, arrayList0, encomendasAceites0);
      parse0.addEncomendasAceites(encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Parse parse0 = new Parse();
      LinkedList<Encomenda> linkedList0 = new LinkedList<Encomenda>();
      Encomenda encomenda0 = new Encomenda();
      linkedList0.add(encomenda0);
      parse0.setEncomendas(linkedList0);
      assertTrue(linkedList0.contains(encomenda0));
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseUtilizador("b}UHuz7");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.getBaseGeral();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("BDGeral", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Parse parse0 = null;
      try {
        parse0 = new Parse((Parse) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Parse parse0 = new Parse();
      List<Encomenda> list0 = parse0.getEncomendas();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseVoluntarios((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Parse parse0 = new Parse();
      parse0.parse();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Parse parse0 = new Parse();
      ArrayList<Locale.LanguageRange> arrayList0 = new ArrayList<Locale.LanguageRange>();
      Locale locale0 = Locale.CHINESE;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) arrayList0, (Collection<String>) set0, locale_FilteringMode0);
      EncomendasAceites encomendasAceites0 = new EncomendasAceites(list0);
      parse0.setEa(encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Parse parse0 = new Parse();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      EncomendasAceites encomendasAceites1 = parse0.parseEncomendasAceites(".ei", encomendasAceites0);
      assertSame(encomendasAceites1, encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Parse parse0 = new Parse();
      EncomendasAceites encomendasAceites0 = parse0.getEa();
      assertNotNull(encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Parse parse0 = new Parse();
      List<String> list0 = parse0.lerFicheiro("{OV1`-]9}\"");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEmpresaTransportes((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLojas((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }
}
