/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 20:55:59 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EncomendaJaExisteException_ESTest extends EncomendaJaExisteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EncomendaJaExisteException encomendaJaExisteException0 = new EncomendaJaExisteException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EncomendaJaExisteException encomendaJaExisteException0 = new EncomendaJaExisteException("EncomendaJaExisteException");
  }
}
