/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jan 25 21:07:30 GMT 2021
 */

package MVC.Controller;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Controller_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "MVC.Controller.Controller"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
    org.evosuite.runtime.util.SystemInUtil.getInstance().initForTestCase(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "/home/pbr/work_ats/analysis/projects/67"); 
    java.lang.System.setProperty("user.home", "/home/pbr"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "pbr"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Controller_ESTest_scaffolding.class.getClassLoader() ,
      "MVC.Views.MenuView",
      "MVC.Models.BaseModels.Utilizador",
      "MVC.Models.BaseModels.LinhaEncomenda",
      "MVC.Input",
      "MVC.Exceptions.InvalidInputException",
      "MVC.Models.Model",
      "MVC.Models.Catalogs.Encomendas",
      "MVC.Models.BaseModels.Produto",
      "MVC.Models.BaseModels.User",
      "MVC.Comparators.MaisKmsComparator",
      "MVC.Models.BaseModels.Encomenda",
      "MVC.Models.BaseModels.GPS",
      "MVC.Models.Catalogs.Transportadoras",
      "MVC.Models.Parse",
      "MVC.Comparators.NumeroVendasComparator",
      "MVC.Views.ListView",
      "MVC.Models.Catalogs.Utilizadores",
      "MVC.Models.BaseModels.Classificacao",
      "MVC.Models.Catalogs.Lojas",
      "MVC.Models.BaseModels.Transportadora",
      "MVC.IView",
      "MVC.Models.BaseModels.VoluntarioMed",
      "MVC.Models.Catalogs.Voluntarios",
      "MVC.Controller.Controller",
      "MVC.Exceptions.NaoExisteException",
      "MVC.Models.BaseModels.Voluntario",
      "MVC.Models.BaseModels.TransportadoraMed",
      "MVC.Views.MessageView",
      "MVC.Models.BaseModels.Loja"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Controller_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "MVC.Controller.Controller",
      "MVC.Views.MessageView",
      "MVC.Models.Model",
      "MVC.Models.Catalogs.Encomendas",
      "MVC.Models.Catalogs.Lojas",
      "MVC.Models.Catalogs.Transportadoras",
      "MVC.Models.Catalogs.Utilizadores",
      "MVC.Models.Catalogs.Voluntarios",
      "MVC.Models.Parse",
      "MVC.Views.MenuView",
      "MVC.Input",
      "MVC.Models.BaseModels.User",
      "MVC.Models.BaseModels.Transportadora",
      "MVC.Models.BaseModels.GPS",
      "MVC.Models.BaseModels.Classificacao",
      "MVC.Views.ListView",
      "MVC.Models.BaseModels.Utilizador",
      "MVC.Models.BaseModels.Loja",
      "MVC.Comparators.NumeroVendasComparator",
      "MVC.Exceptions.NaoExisteException",
      "MVC.Comparators.MaisKmsComparator",
      "MVC.Models.BaseModels.Encomenda",
      "MVC.Models.BaseModels.Voluntario",
      "MVC.Models.BaseModels.VoluntarioMed",
      "MVC.Models.BaseModels.TransportadoraMed"
    );
  }
}
