/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:08:35 GMT 2021
 */

package MVC.Models.BaseModels;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import MVC.Models.BaseModels.VoluntarioMed;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VoluntarioMed_ESTest extends VoluntarioMed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed();
      voluntarioMed0.setVelocidadeMed((-575.8123971851));
      VoluntarioMed voluntarioMed1 = voluntarioMed0.clone();
      assertFalse(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("", ">S4gwU`B6)", 0.0, 0.0, 1546.180438230889, true);
      VoluntarioMed voluntarioMed1 = voluntarioMed0.clone();
      assertTrue(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("MVC.Models.BaseModels.VoluntarioMed", "MVC.Models.BaseModels.VoluntarioMed", 0.0, 0.0, (-5501.0), true);
      VoluntarioMed voluntarioMed1 = voluntarioMed0.clone();
      assertTrue(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("TY", "x+O}>d70a%j", 0.0, 0.0, 0.0, true);
      voluntarioMed0.classificaVoluntario(379);
      VoluntarioMed voluntarioMed1 = voluntarioMed0.clone();
      assertTrue(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("+|*.(sr.l@", "R/j;b", 2.0, 2.0, 0.0, true);
      voluntarioMed0.classificaVoluntario((-3023));
      VoluntarioMed voluntarioMed1 = voluntarioMed0.clone();
      assertTrue(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed();
      voluntarioMed0.setEstaLivre(false);
      VoluntarioMed voluntarioMed1 = voluntarioMed0.clone();
      assertFalse(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed();
      boolean boolean0 = voluntarioMed0.aceitoTrasnporteMedicamentos();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("", "Transporta Medicamentos: ", 119.15227019709, 119.15227019709, (-1.0), true);
      boolean boolean0 = voluntarioMed0.aceitoTrasnporteMedicamentos();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("TY", "x+O}>d70a%j", 0.0, 0.0, 0.0, true);
      VoluntarioMed voluntarioMed1 = new VoluntarioMed(voluntarioMed0);
      assertTrue(voluntarioMed1.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed("VqCCWP;Nt", "VqCCWP;Nt", (-8), (-8), (-8), true);
      String string0 = voluntarioMed0.toString();
      assertEquals("Voluntario{\nC\u00F3digo: VqCCWP;Nt\nNome: VqCCWP;Nt\nGPS: (-8.0,-8.0)\nRaio: -8.0\nClassificacao:0.00\n}Transporta Medicamentos: true\n", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = new VoluntarioMed();
      voluntarioMed0.aceitaMedicamentos(false);
      assertFalse(voluntarioMed0.aceitoTrasnporteMedicamentos());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VoluntarioMed voluntarioMed0 = null;
      try {
        voluntarioMed0 = new VoluntarioMed((VoluntarioMed) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.BaseModels.User", e);
      }
  }
}
