/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:05:32 GMT 2021
 */

package MVC.Comparators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import MVC.Comparators.NumeroVendasComparator;
import MVC.Models.BaseModels.Utilizador;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NumeroVendasComparator_ESTest extends NumeroVendasComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NumeroVendasComparator numeroVendasComparator0 = new NumeroVendasComparator();
      Utilizador utilizador0 = new Utilizador("RvB", "RvB", (-3507.525506), (-3507.525506));
      Utilizador utilizador1 = new Utilizador();
      int int0 = numeroVendasComparator0.compare(utilizador0, utilizador1);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NumeroVendasComparator numeroVendasComparator0 = new NumeroVendasComparator();
      Utilizador utilizador0 = new Utilizador();
      // Undeclared exception!
      try { 
        numeroVendasComparator0.compare((Utilizador) null, utilizador0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Comparators.NumeroVendasComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NumeroVendasComparator numeroVendasComparator0 = new NumeroVendasComparator();
      Utilizador utilizador0 = new Utilizador();
      Utilizador utilizador1 = new Utilizador(utilizador0);
      utilizador1.setNumeroEncomendas((-33));
      int int0 = numeroVendasComparator0.compare(utilizador0, utilizador1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NumeroVendasComparator numeroVendasComparator0 = new NumeroVendasComparator();
      Utilizador utilizador0 = new Utilizador();
      Utilizador utilizador1 = new Utilizador(utilizador0);
      utilizador1.setNumeroEncomendas((-33));
      int int0 = numeroVendasComparator0.compare(utilizador1, utilizador0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NumeroVendasComparator numeroVendasComparator0 = new NumeroVendasComparator();
      Utilizador utilizador0 = new Utilizador();
      int int0 = numeroVendasComparator0.compare(utilizador0, utilizador0);
      assertEquals(0, int0);
  }
}
