- name: Install nginx
  apt:
    name: nginx
    state: present

# If we are gonna use ssl / https we need this steps to work too
#- name: Install snapd

#- name: snap install core & refresh core

#- name: Install Certbot

#- name: Prepare the Certbot command

- name: Copy template into correct location 
  template:
    src: mm_nginx_config
    dest: "/etc/nginx/sites-available/mattermost"
    owner: root
    group: root

- name: Delete default nginx file
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Create symlink for the mattermost config file
  file:
    src: "/etc/nginx/sites-available/mattermost"
    dest: "/etc/nginx/sites-enabled/mattermost"
    owner: root
    group: root
    state: link
  notify: restart nginx