/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 20:55:05 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Empresa_ESTest extends Empresa_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setNif("");
      empresa0.getNif();
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setCustokm(586.099287617);
      double double0 = empresa0.getCustokm();
      assertEquals(586.099287617, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Empresa empresa0 = new Empresa("", "", "", (Ponto2D) null, 2.0, 0, 0, "", (-3134.43), (-454.8604418));
      double double0 = empresa0.getCustokm();
      assertEquals((-3134.43), empresa0.getCustokg(), 0.01);
      assertEquals((-454.8604418), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      
      empresa0.setCustokg(1.0);
      double double0 = empresa0.getCustokg();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setCustokg((-217.338895356903));
      double double0 = empresa0.getCustokg();
      assertEquals((-217.338895356903), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setVelmed(829);
      empresa0.clone();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setVelmed((-125));
      empresa0.clone();
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setRaio((-217.338895356903));
      empresa0.clone();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setLicMedicamentos(1);
      empresa0.clone();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setLicMedicamentos((-1));
      empresa0.clone();
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setCustokm(586.099287617);
      empresa0.clone();
      assertEquals(586.099287617, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      
      empresa0.setCustokg(1.0);
      empresa0.clone();
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Empresa empresa0 = new Empresa("", "", "", (Ponto2D) null, 2.0, 0, 0, "", (-3134.43), (-454.8604418));
      Empresa empresa1 = empresa0.clone();
      assertEquals((-454.8604418), empresa1.getCustokm(), 0.01);
      assertEquals((-3134.43), empresa0.getCustokg(), 0.01);
      assertEquals((-454.8604418), empresa0.getCustokm(), 0.01);
      assertEquals((-3134.43), empresa1.getCustokg(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Empresa empresa0 = new Empresa("sr6+.i)-0e", "lvsQ{A2>9zg},/s%u]", "", (Ponto2D) null, 0.0, 0, 0, "", (-428.1641169), 696.2);
      // Undeclared exception!
      try { 
        empresa0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Perfil", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Empresa empresa0 = null;
      try {
        empresa0 = new Empresa((Empresa) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Perfil", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      Empresa empresa1 = new Empresa(empresa0);
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      double double0 = empresa0.getCustokm();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.getNif();
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      double double0 = empresa0.getCustokg();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      empresa0.setNif("Perfil: \n\n\n(0.0,0.0)\nRaio de a\u00E7ao: 0.0\nVelocidade media: 0\nLicen\u00E7a de transporte de medicamentos: 0\nNif: null\nCusto por km: 0.0\nCusto por quilo: 0.0\n");
      empresa0.getNif();
      assertEquals(0.0, empresa0.getCustokm(), 0.01);
      assertEquals(0.0, empresa0.getCustokg(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Empresa empresa0 = new Empresa();
      String string0 = empresa0.toString();
      assertEquals("Perfil: \n\n\n(0.0,0.0)\nRaio de a\u00E7ao: 0.0\nVelocidade media: 0\nLicen\u00E7a de transporte de medicamentos: 0\nNif: null\nCusto por km: 0.0\nCusto por quilo: 0.0\n", string0);
  }
}
