/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 20:56:00 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NaoSeEncontraRaioException_ESTest extends NaoSeEncontraRaioException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NaoSeEncontraRaioException naoSeEncontraRaioException0 = new NaoSeEncontraRaioException("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NaoSeEncontraRaioException naoSeEncontraRaioException0 = new NaoSeEncontraRaioException();
  }
}
