/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:07:30 GMT 2021
 */

package MVC.Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import MVC.Controller.Controller;
import MVC.Models.Model;
import MVC.Views.MessageView;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Controller_ESTest extends Controller_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.start();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Controller controller0 = new Controller();
      Model model0 = new Model();
      controller0.setModel(model0);
      SystemInUtil.addInputLine("4");
      // Undeclared exception!
      try { 
        controller0.start();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Controller controller0 = new Controller();
      Model model0 = new Model();
      SystemInUtil.addInputLine("gTo4");
      controller0.setModel(model0);
      // Undeclared exception!
      try { 
        controller0.start();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Controller controller0 = new Controller();
      Model model0 = new Model();
      controller0.setModel(model0);
      SystemInUtil.addInputLine("0");
      controller0.start();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.setUser("gTo4");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Controller controller0 = new Controller();
      MessageView messageView0 = new MessageView();
      controller0.setView(messageView0);
  }
}
