/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 21:03:35 GMT 2021
 */

package MVC.Models.BaseModels;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import MVC.Models.BaseModels.Produto;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Produto_ESTest extends Produto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Produto produto0 = new Produto("", "", 0.0, true);
      boolean boolean0 = produto0.isMedicamento();
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Produto produto0 = new Produto();
      double double0 = produto0.getPrecoPorQuant();
      assertEquals(0.0, double0, 0.01);
      assertFalse(produto0.isMedicamento());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Produto produto0 = new Produto("\nCodigo: ", "\nCodigo: ", (-1.0), true);
      double double0 = produto0.getPrecoPorQuant();
      assertTrue(produto0.isMedicamento());
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Produto produto0 = new Produto((String) null, "", 1.0);
      produto0.setNome((String) null);
      produto0.getNome();
      assertFalse(produto0.isMedicamento());
      assertEquals(1.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Produto produto0 = new Produto("", "O3sVp%U_4x#fJ`LQ", (-1.0), false);
      String string0 = produto0.getNome();
      assertEquals((-1.0), produto0.getPrecoPorQuant(), 0.01);
      assertEquals("", produto0.getCod());
      assertEquals("O3sVp%U_4x#fJ`LQ", string0);
      assertFalse(produto0.isMedicamento());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Produto produto0 = new Produto();
      produto0.setCod("z`[S/K,B_P:~?");
      produto0.getCod();
      assertFalse(produto0.isMedicamento());
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Produto produto0 = new Produto();
      produto0.getCod();
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
      assertFalse(produto0.isMedicamento());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Produto produto0 = new Produto((String) null, "'uC$5h 3;PY%f", 2707.140687, true);
      Produto produto1 = produto0.clone();
      assertTrue(produto1.isMedicamento());
      assertEquals(2707.140687, produto0.getPrecoPorQuant(), 0.01);
      assertEquals(2707.140687, produto1.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Produto produto0 = new Produto((String) null, "", 1.0);
      Produto produto1 = produto0.clone();
      assertEquals(1.0, produto1.getPrecoPorQuant(), 0.01);
      assertFalse(produto1.isMedicamento());
      assertEquals(1.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Produto produto0 = new Produto();
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
      
      produto0.setPrecoPorQuant((-1.0));
      produto0.clone();
      assertEquals((-1.0), produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Produto produto0 = null;
      try {
        produto0 = new Produto((Produto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MVC.Models.BaseModels.Produto", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 1.0, false);
      produto0.getCod();
      assertFalse(produto0.isMedicamento());
      assertEquals(1.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Produto produto0 = new Produto((String) null, "", 1.0);
      String string0 = produto0.getNome();
      assertFalse(produto0.isMedicamento());
      assertEquals(1.0, produto0.getPrecoPorQuant(), 0.01);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 1.0, false);
      boolean boolean0 = produto0.isMedicamento();
      assertEquals(1.0, produto0.getPrecoPorQuant(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Produto produto0 = new Produto((String) null, "", 1.0);
      double double0 = produto0.getPrecoPorQuant();
      assertEquals(1.0, double0, 0.01);
      assertFalse(produto0.isMedicamento());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Produto produto0 = new Produto();
      Produto produto1 = new Produto(produto0);
      assertFalse(produto1.isMedicamento());
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Produto produto0 = new Produto();
      boolean boolean0 = produto0.equals("");
      assertFalse(produto0.isMedicamento());
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, (-1895.32799664), true);
      boolean boolean0 = produto0.equals((Object) null);
      assertTrue(produto0.isMedicamento());
      assertFalse(boolean0);
      assertEquals((-1895.32799664), produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 0.0);
      boolean boolean0 = produto0.equals(produto0);
      assertTrue(boolean0);
      assertFalse(produto0.isMedicamento());
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Produto produto0 = new Produto();
      Produto produto1 = new Produto("J<C)$rztw;xC", "\nCodigo: \nProduto: \nPreco por quantidade: 0.0", 885.4284948);
      boolean boolean0 = produto0.equals(produto1);
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
      assertEquals("J<C)$rztw;xC", produto1.getCod());
      assertFalse(boolean0);
      assertEquals("\nCodigo: \nProduto: \nPreco por quantidade: 0.0", produto1.getNome());
      assertEquals(885.4284948, produto1.getPrecoPorQuant(), 0.01);
      assertFalse(produto0.isMedicamento());
      assertFalse(produto1.isMedicamento());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 0.0);
      produto0.setMedicamento(false);
      assertFalse(produto0.isMedicamento());
      assertEquals(0.0, produto0.getPrecoPorQuant(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Produto produto0 = new Produto();
      String string0 = produto0.toString();
      assertEquals("\nCodigo: \nProduto: \nPreco por quantidade: 0.0", string0);
      assertFalse(produto0.isMedicamento());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 0.0);
      Produto produto1 = produto0.clone();
      // Undeclared exception!
      try { 
        produto0.equals(produto1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
